---
 - name: Install HAProxy
   apt:
     name: haproxy
     state: present

 - name: HAProxy config file
   template:
     src: haproxy.cfg.j2
     dest: /etc/haproxy/haproxy.cfg
     owner: root
     group: root
     mode: 0644
   notify: Restart HAProxy service
