---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install app components
  apt: name={{item}} state=present
  with_items:
    - supervisor

- name: stop supervisor initial 
  service: name=supervisor state=stopped
     
- name: create celery beat file
  copy: content="" dest="{{ app_path }}/celerybeat.pid mode=0777"
  when: "'app_master' in group_names"

- name: copy supervisor conf
  template: src=supervisor_master.conf.j2 dest=/etc/supervisor/conf.d/supervisor.conf mode=0755
  when: "'app_master' in group_names"

- name: copy supervisor conf
  template: src=supervisor_server.conf.j2 dest=/etc/supervisor/conf.d/supervisor.conf mode=0755
  when: "'app_server' in group_names"

- name: copy supervisor conf
  template: src=supervisor_worker.conf.j2 dest=/etc/supervisor/conf.d/supervisor.conf mode=0755
  when: "'worker' in group_names"

# Handlers weren't working for supervisor.  Restart for supervisor isn't working.
# Weird stuff with supervisor.sock so need to start / stop / start to make sure it exists

- name: start supervisor initial
  service: name=supervisor state=started

- name: reread supervisor
  command: supervisorctl reread
      
- name: update supervisor
  command: supervisorctl update

- name: ensure supervisor stopped
  service: name=supervisor state=stopped
     
- name: ensure supervisor started
  service: name=supervisor state=started
