---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install app components
  apt: name={{item}} state=present
  with_items:
    - libpq-dev
    - git
    - python-dev
    - python-psycopg2
    - python-pip
    - python-virtualenv
    - supervisor

- name: ensure git repo is present
  git:
    repo: "https://github.com/burnsie7/wcdemo.git"
    dest: /var/www/wcdemo # TODO: base_dir + app_path

- name: copy settings.py
  template: src=settings.py.j2 dest="{{ app_path }}/perfdemo/settings.py" mode=0755

- name: create virtual env
  command: virtualenv "{{ app_path }}/venv" -p python2.7 creates="{{ app_path }}/venv"

- name: install requirements
  pip:
    requirements="{{ app_path }}/requirements.txt"
    executable="{{ app_path }}/venv/bin/pip"

# TODO: only one host can run django migrate.  Create a separate role w/ django[0] that does the migrations or something.
- name: django migrate
  django_manage:
    command: migrate
    virtualenv: "{{ app_path }}/venv"
    app_path: "{{ app_path }}"

- name: django init_db 
  django_manage:
    command: init_db
    virtualenv: "{{ app_path }}/venv"
    app_path: "{{ app_path }}"

- name: create celery beat file
  copy: content="" dest="{{ app_path }}/celerybeat.pid mode=0777"

- name: stop supervisor initial 
  service: name=supervisor state=stopped
     
- name: copy supervisor conf
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/supervisor.conf mode=0755

# Handlers weren't working for supervisor.  Restart for supervisor isn't working.
# Weird stuff with supervisor.sock so need to start / stop / start to make sure it exists

- name: start supervisor initial
  service: name=supervisor state=started

- name: reread supervisor
  command: supervisorctl reread
      
- name: update supervisor
  command: supervisorctl update

- name: ensure supervisor stopped
  service: name=supervisor state=stopped
     
- name: ensure supervisor started
  service: name=supervisor state=started
