---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install app components
  apt: name={{item}} state=present
  with_items:
    - libpq-dev
    - git
    - python-dev
    - python-psycopg2
    - python-pip
    - python-virtualenv

- name: ensure git repo is present
  git:
    repo: "https://github.com/burnsie7/wcdemo.git"
    dest: /var/www/wcdemo # TODO: base_dir + app_path

- name: copy settings.py
  template: src=settings.py.j2 dest="{{ app_path }}/perfdemo/settings.py" mode=0755

- name: create virtual env
  command: virtualenv "{{ app_path }}/venv" -p python2.7 creates="{{ app_path }}/venv"

- name: install requirements
  pip:
    requirements="{{ app_path }}/requirements.txt"
    executable="{{ app_path }}/venv/bin/pip"
