---
- hosts: database
  become: true
  vars:
    datadog_checks:
      postgres:
        init_config:
        instances:
          - host: localhost
            port: 5432
            username: "{{ agent_user }}"
            password: "{{ agent_pass }}"
            tags:
              - test
              - env:ans-demo
  roles:
    - postgres
    - Datadog.datadog
