---
- hosts: database
  become: true
  vars:
    datadog_config:
      tags: "postgres, wcd"
      log_level: INFO
      apm_enabled: "true" # has to be set as a string
    datadog_checks:
      postgres:
        init_config:
        instances:
          - host: localhost
            port: 5432
            username: "{{ agent_user }}"
            password: "{{ agent_pass }}"
            tags:
              - env:demo
  roles:
    - sshkeys
    - postgres
    - Datadog.datadog
