---
  - hosts: loadbalancer
    gather_facts: true
  - hosts: haproxy
    remote_user: ubuntu
    become: true
    vars:
      datadog_config:
        tags: "haproxy, wcd"
        log_level: INFO
        apm_enabled: "true" # has to be set as a string
      datadog_checks:
        haproxy:
          init_config:
          instances:
            - url: http://localhost/haproxy_stats
              username: stats_user
              password: stats_pass
              tags:
                - env:demo
    roles:
      - Datadog.datadog
      - sshkeys
      - haproxy
