---
- hosts: app
  gather_facts: true
- hosts: loadbalancer
  become: true
  vars:
    datadog_config:
      tags: "nginx, wcd"
      log_level: INFO
      apm_enabled: "true" # has to be set as a string
    datadog_checks:
      nginx:
        init_config:
        instances:
          - nginx_status_url: http://localhost/nginx_status/
  roles:
    - Datadog.datadog
    - nginx

