---
- hosts: redis
  become: true
  vars:
    datadog_checks:
      redisdb:
        init_config:
        instances:
          - host: localhost
            port: 6379
  roles:
    - Datadog.datadog
    - redisdb
