---
- hosts: redis
  become: true
  vars:
    datadog_config:
      tags: "redisdb, wcd"
      log_level: INFO
      apm_enabled: "true" # has to be set as a string
    datadog_checks:
      redisdb:
        init_config:
        instances:
          - host: localhost
            port: 6379
            tags:
              - env:demo
  roles:
    - sshkeys
    - Datadog.datadog
    - redisdb
