---
- hosts: all
  become: true
  gather_facts: true
- import_playbook: database.yml
- import_playbook: redisdb.yml
- import_playbook: loadbalancer.yml
- import_playbook: haproxy.yml
- import_playbook: wcdemo.yml
- import_playbook: django_status.yml
