---
- hosts: all
  gather_facts: true

- hosts: app
  gather_facts: false
  become: true
  vars:
    datadog_config:
      tags: "django, wcd, {{ group_names }}"
      log_level: INFO
      apm_enabled: "true" # has to be set as a string
    # TODO: Leave off of workers using vars
    datadog_checks:
      gunicorn:
        init_config:
        instances:
          - proc_name: perfdemo
  roles:
    - sshkeys
    - Datadog.datadog
    - django

# django_migrate does not support 'when' so doing this instead. not great but whatevs.
- hosts: ["app_master"]
  gather_facts: false
  tasks:
    - name: django migrate
      django_manage:
        command: migrate
        virtualenv: "{{ app_path }}/venv"
        app_path: "{{ app_path }}"
    
    - name: django init_db 
      django_manage:
        command: init_db
        virtualenv: "{{ app_path }}/venv"
        app_path: "{{ app_path }}"

- hosts: app
  gather_facts: false
  become: true
  roles:
    - supervisor
