---
# TODO: Need only one django migration and different django roles for sending tasks, etc.
- hosts: all
  gather_facts: true
- hosts: app
  become: true
  vars:
    dbname: "{{ db_name }}"
    dbuser: "{{ db_user }}"
    dbpassword: "{{ db_pass }}"
    datadog_api_key: "{{ datadog_api }}"
    datadog_checks:
      gunicorn:
        init_config:
        instances:
          - proc_name: perfdemo
  roles:
    - Datadog.datadog
    - django
