---
- hosts: all
  gather_facts: true
- hosts: ["app-master", "app-server"]
  become: true
  vars:
    datadog_checks:
      gunicorn:
        init_config:
        instances:
          - proc_name: perfdemo
  roles:
    - Datadog.datadog

- hosts: ["app-master", "app-server", "worker"]
  become: true
  vars:
  roles:
    - django

# django_migrate does not support 'when' so doing this instead. not great but whatevs.
- hosts: ["app-master"]
  tasks:
    - name: django migrate
      django_manage:
        command: migrate
        virtualenv: "{{ app_path }}/venv"
        app_path: "{{ app_path }}"
    
    - name: django init_db 
      django_manage:
        command: init_db
        virtualenv: "{{ app_path }}/venv"
        app_path: "{{ app_path }}"

- hosts: ["app-master", "app-server", "worker"]
  become: true
  roles:
    - supervisor
